schema: "classroom50/repo-config/v1"
classroom: "data-tech-analytics"
assignment: "hello-github"
owner:
  username: "CanhKhoQua"
  id: 111905138
  accepted_at: "2026-08-26T14:55:29Z"
source:
  owner: "IT4063C-Fall2026"
  owner_id: 320344006
  repo: "hello-github"
  branch: "main"
